### ISSUE TITLE
 from Crypto.Cipher import AES

### ISSUE THREAD

**Issue by Ahmadjerj** [xiaotsai/RedLine-Stealer#1]
So when I try to run it I get  from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
![RedLine-Stealer-main – redline py 12_8_2022 4_15_54 PM](https://user-images.githubusercontent.com/72747814/206470143-85e8bcf8-56cb-4276-905a-37e225ffbcfd.png)

**Comment by xiaotsai** [comment]
Did you use pip install?

**Comment by xiaotsai** [comment]
try it `pip install pycrypto`

**Comment by xiaotsai** [comment]
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
